module_name: Dash Activity
compatible_versions: 1.0.0+
author: thirty bees
category: statistics
tags:
  - dashboard
  - shop activity
  - stats
  - statistics
description_short: The dash activity module allows you to
description: description.md
images:
  - image-1.png
license: AFL